### ISSUE TITLE
error running editioncrafter locally

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/editioncrafter-cli#17]
After installing editioncrafter-cli on Naomi's WSL machine, we ran this command: `editioncrafter process ../editioncrafter-data/texts/fr640_3r-3v-example.xml . http://localhost:8080` and got the following error:

```
ReferenceError: structuredClone is not defined: ReferenceError: structuredClone is not defined
    at renderManifest (/mnt/c/Users/naomi/Github/editioncrafter-cli/src/render.js:139:22)
    at renderTEIDocument (/mnt/c/Users/naomi/Github/editioncrafter-cli/src/render.js:274:22)
    at processTEIDocument (/mnt/c/Users/naomi/Github/editioncrafter-cli/src/index.js:17:20)
    at run (/mnt/c/Users/naomi/Github/editioncrafter-cli/src/index.js:27:9)
    at editionCrafterCLI (/mnt/c/Users/naomi/Github/editioncrafter-cli/src/index.js:109:9)
    at Object.<anonymous> (/mnt/c/Users/naomi/Github/editioncrafter-cli/editioncrafter:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

**Comment by njr2128** [comment]
Updating nmp did not resolve the issue

**Comment by njr2128** [comment]
this may have to do with incompatibility of node and the version of ubuntu I am using (18). This is the error I receive after attempting to upgrade node to node18:
`node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)`

**Comment by NickLaiacona** [comment]
@camdendotlol can you have a look at this and also #18 ?

**Comment by camdendotlol** [comment]
Going by https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility, it looks like `structuredClone` is available starting in Node 17 (18 being the earliest LTS release).

There should be a drop-in polyfill easily available somewhere - I'll see if I can add it so we can package the `structedClone` function with the app and remove the need for Node >= 18.

**Comment by NickLaiacona** [comment]
Fixed by structuredClone polyfill
